#!/bin/bash

# to ensure this works both on the command line and from finder
cd $(dirname $0) 
root=$(pwd)

# cd $root/rust-native/
# cargo run

cd $root/app/core/
npm install

cd $root/app/
npm install

source $root/run