#!/bin/bash

# to ensure this works both on the command line and from finder
cd $(dirname $0) 
root=$(pwd)

# cd $root/rust-native/
# cargo run

cd $root/app/core/
npm run build -- --release

cd $root/app/
npm start
