#!/bin/bash

# to ensure this works both on the command line and from finder

cd $(dirname $0) 
root=$(pwd)

cd $root/neon/
npm run build -- --release

cd $root/rust-native/
cargo run

cd $root/electron/
npm start
