[package]
name = "procmod-rust"
version = "0.1.0"
authors = ["FraserLee <tomatoesneverlie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.7.3"
sdl2 = "0.34.5"
