[package]
name = "procmodl-core"
version = "0.1.0"
license = "UNLICENSED"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
yaml-rust = "0.4.5"

[dependencies.neon]
version = "0.8"
default-features = false
features = ["napi-6"]
